feat: add CDN proto
skyra-project/wardrobe pull request #4
Opened 2021-08-03 23:07 UTC by Tylertron1998

2021-08-03 23:17 UTC, kyranet requested changes

2021-08-03 23:17 UTC, kyranet commented on protos/cdn.proto
> +}
I stg whatever you use doesn't add EOFs.
```suggestion
}

```

2021-08-03 23:19 UTC, kyranet submitted a review, later dismissed

2021-08-04 08:14 UTC, Favna approved these changes

2021-08-08 13:42 UTC, Favna approved these changes

2021-08-08 13:53 UTC, kyranet approved these changes

2021-08-08 13:55 UTC, merged